CREATE TABLE USER_DETAILS(
user_id NUMERIC(4) IDENTITY (1001,1) NOT NULL CONSTRAINT USER_DETAILS_user_id_pk PRIMARY KEY,
name VARCHAR(30) NOT NULL,
login_id VARCHAR(30) NOT NULL CONSTRAINT USER_login_id UNIQUE,
password VARCHAR(20) NOT NULL,
contact NUMERIC(10) NOT NULL,
reg DATETIME
)

CREATE TABLE ORDER_DETAILS(
order_id NUMERIC(4) IDENTITY (1,1) NOT NULL CONSTRAINT ORDER_DETAILS_order_id_pk PRIMARY KEY,
order_category VARCHAR(4) NOT NULL,
order_type VARCHAR(6) NOT NULL,
order_time DATETIME,
quantity NUMERIC(15) NOT NULL,
price NUMERIC(15) not null,
user_id NUMERIC(4) NOT NULL CONSTRAINT ORDER_DETAILS_user_id_fk REFERENCES USER_DETAILS(user_id),
order_status VARCHAR(12) NOT NULL,
aon VARCHAR(3) NOT NULL,
remaining_quantity NUMERIC(10) NOT NULL
)

CREATE TABLE TRADE_DETAILS(
trade_id Numeric(4) IDENTITY(2001,1) NOT NULL CONSTRAINT TRADE_DETAILS_trade_id_pk PRIMARY KEY,
order_id_buy NUMERIC(4) NOT NULL CONSTRAINT TRADE_DETAILS_order_id_buy_fk REFERENCES ORDER_DETAILS(order_id),
order_id_sell NUMERIC(4) NOT NULL CONSTRAINT TRADE_DETAILS_order_id_sell_fk REFERENCES ORDER_DETAILS(order_id),
traded_price NUMERIC(15) NOT NULL,
traded_quantity NUMERIC(15) NOT NULL,
traded_time	DATETIME NOT NULL
)

drop table TRADE_DETAILS
drop table USER_DETAILS
drop table ORDER_DETAILS


SELECT * FROM ORDER_DETAILS
SELECT * FROM TRADE_DETAILS
SELECT * FROM USER_DETAILS

SP_HELP 'TRADE_DETAILS'
SP_HELP 'ORDER_DETAILS'
SP_HELP 'USER_DETAILS'


